// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package serverpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SignSpot_SignSpotType int32

const (
	SignSpot_Museum SignSpot_SignSpotType = 0
)

var SignSpot_SignSpotType_name = map[int32]string{
	0: "Museum",
}
var SignSpot_SignSpotType_value = map[string]int32{
	"Museum": 0,
}

func (x SignSpot_SignSpotType) String() string {
	return proto.EnumName(SignSpot_SignSpotType_name, int32(x))
}
func (SignSpot_SignSpotType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_rpc_7575a4de3a1e3c52, []int{3, 0}
}

type PhotoPredictRequest_PhotoType int32

const (
	PhotoPredictRequest_PNG PhotoPredictRequest_PhotoType = 0
	PhotoPredictRequest_JPG PhotoPredictRequest_PhotoType = 1
)

var PhotoPredictRequest_PhotoType_name = map[int32]string{
	0: "PNG",
	1: "JPG",
}
var PhotoPredictRequest_PhotoType_value = map[string]int32{
	"PNG": 0,
	"JPG": 1,
}

func (x PhotoPredictRequest_PhotoType) String() string {
	return proto.EnumName(PhotoPredictRequest_PhotoType_name, int32(x))
}
func (PhotoPredictRequest_PhotoType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_rpc_7575a4de3a1e3c52, []int{4, 0}
}

type AuthRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_7575a4de3a1e3c52, []int{0}
}
func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (dst *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(dst, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AuthRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AuthRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AuthResponse struct {
	RequireLogin         bool     `protobuf:"varint,1,opt,name=require_login,json=requireLogin" json:"require_login,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	Msg                  string   `protobuf:"bytes,3,opt,name=msg" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_7575a4de3a1e3c52, []int{1}
}
func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (dst *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(dst, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetRequireLogin() bool {
	if m != nil {
		return m.RequireLogin
	}
	return false
}

func (m *AuthResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AuthResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type GeoPosition struct {
	Latitude             float64  `protobuf:"fixed64,1,opt,name=latitude" json:"latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,2,opt,name=longitude" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeoPosition) Reset()         { *m = GeoPosition{} }
func (m *GeoPosition) String() string { return proto.CompactTextString(m) }
func (*GeoPosition) ProtoMessage()    {}
func (*GeoPosition) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_7575a4de3a1e3c52, []int{2}
}
func (m *GeoPosition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeoPosition.Unmarshal(m, b)
}
func (m *GeoPosition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeoPosition.Marshal(b, m, deterministic)
}
func (dst *GeoPosition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeoPosition.Merge(dst, src)
}
func (m *GeoPosition) XXX_Size() int {
	return xxx_messageInfo_GeoPosition.Size(m)
}
func (m *GeoPosition) XXX_DiscardUnknown() {
	xxx_messageInfo_GeoPosition.DiscardUnknown(m)
}

var xxx_messageInfo_GeoPosition proto.InternalMessageInfo

func (m *GeoPosition) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *GeoPosition) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type SignSpot struct {
	Id                   uint64                `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name                 string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Type                 SignSpot_SignSpotType `protobuf:"varint,3,opt,name=type,enum=serverpb.SignSpot_SignSpotType" json:"type,omitempty"`
	Geo                  *GeoPosition          `protobuf:"bytes,4,opt,name=geo" json:"geo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SignSpot) Reset()         { *m = SignSpot{} }
func (m *SignSpot) String() string { return proto.CompactTextString(m) }
func (*SignSpot) ProtoMessage()    {}
func (*SignSpot) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_7575a4de3a1e3c52, []int{3}
}
func (m *SignSpot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignSpot.Unmarshal(m, b)
}
func (m *SignSpot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignSpot.Marshal(b, m, deterministic)
}
func (dst *SignSpot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignSpot.Merge(dst, src)
}
func (m *SignSpot) XXX_Size() int {
	return xxx_messageInfo_SignSpot.Size(m)
}
func (m *SignSpot) XXX_DiscardUnknown() {
	xxx_messageInfo_SignSpot.DiscardUnknown(m)
}

var xxx_messageInfo_SignSpot proto.InternalMessageInfo

func (m *SignSpot) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SignSpot) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SignSpot) GetType() SignSpot_SignSpotType {
	if m != nil {
		return m.Type
	}
	return SignSpot_Museum
}

func (m *SignSpot) GetGeo() *GeoPosition {
	if m != nil {
		return m.Geo
	}
	return nil
}

type PhotoPredictRequest struct {
	Type                 PhotoPredictRequest_PhotoType `protobuf:"varint,1,opt,name=type,enum=serverpb.PhotoPredictRequest_PhotoType" json:"type,omitempty"`
	Data                 []byte                        `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Base64Encoded        bool                          `protobuf:"varint,3,opt,name=base64_encoded,json=base64Encoded" json:"base64_encoded,omitempty"`
	Geo                  *GeoPosition                  `protobuf:"bytes,4,opt,name=geo" json:"geo,omitempty"`
	AcquireText          bool                          `protobuf:"varint,5,opt,name=acquire_text,json=acquireText" json:"acquire_text,omitempty"`
	AcquireAudio         bool                          `protobuf:"varint,6,opt,name=acquire_audio,json=acquireAudio" json:"acquire_audio,omitempty"`
	AcquireVideo         bool                          `protobuf:"varint,7,opt,name=acquire_video,json=acquireVideo" json:"acquire_video,omitempty"`
	MaxLimits            int32                         `protobuf:"varint,8,opt,name=max_limits,json=maxLimits" json:"max_limits,omitempty"`
	Language             string                        `protobuf:"bytes,9,opt,name=language" json:"language,omitempty"`
	Site                 string                        `protobuf:"bytes,10,opt,name=site" json:"site,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *PhotoPredictRequest) Reset()         { *m = PhotoPredictRequest{} }
func (m *PhotoPredictRequest) String() string { return proto.CompactTextString(m) }
func (*PhotoPredictRequest) ProtoMessage()    {}
func (*PhotoPredictRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_7575a4de3a1e3c52, []int{4}
}
func (m *PhotoPredictRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhotoPredictRequest.Unmarshal(m, b)
}
func (m *PhotoPredictRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhotoPredictRequest.Marshal(b, m, deterministic)
}
func (dst *PhotoPredictRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhotoPredictRequest.Merge(dst, src)
}
func (m *PhotoPredictRequest) XXX_Size() int {
	return xxx_messageInfo_PhotoPredictRequest.Size(m)
}
func (m *PhotoPredictRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PhotoPredictRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PhotoPredictRequest proto.InternalMessageInfo

func (m *PhotoPredictRequest) GetType() PhotoPredictRequest_PhotoType {
	if m != nil {
		return m.Type
	}
	return PhotoPredictRequest_PNG
}

func (m *PhotoPredictRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *PhotoPredictRequest) GetBase64Encoded() bool {
	if m != nil {
		return m.Base64Encoded
	}
	return false
}

func (m *PhotoPredictRequest) GetGeo() *GeoPosition {
	if m != nil {
		return m.Geo
	}
	return nil
}

func (m *PhotoPredictRequest) GetAcquireText() bool {
	if m != nil {
		return m.AcquireText
	}
	return false
}

func (m *PhotoPredictRequest) GetAcquireAudio() bool {
	if m != nil {
		return m.AcquireAudio
	}
	return false
}

func (m *PhotoPredictRequest) GetAcquireVideo() bool {
	if m != nil {
		return m.AcquireVideo
	}
	return false
}

func (m *PhotoPredictRequest) GetMaxLimits() int32 {
	if m != nil {
		return m.MaxLimits
	}
	return 0
}

func (m *PhotoPredictRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *PhotoPredictRequest) GetSite() string {
	if m != nil {
		return m.Site
	}
	return ""
}

type PhotoPredictResponse struct {
	Results              []*PhotoPredictResponse_Result `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *PhotoPredictResponse) Reset()         { *m = PhotoPredictResponse{} }
func (m *PhotoPredictResponse) String() string { return proto.CompactTextString(m) }
func (*PhotoPredictResponse) ProtoMessage()    {}
func (*PhotoPredictResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_7575a4de3a1e3c52, []int{5}
}
func (m *PhotoPredictResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhotoPredictResponse.Unmarshal(m, b)
}
func (m *PhotoPredictResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhotoPredictResponse.Marshal(b, m, deterministic)
}
func (dst *PhotoPredictResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhotoPredictResponse.Merge(dst, src)
}
func (m *PhotoPredictResponse) XXX_Size() int {
	return xxx_messageInfo_PhotoPredictResponse.Size(m)
}
func (m *PhotoPredictResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PhotoPredictResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PhotoPredictResponse proto.InternalMessageInfo

func (m *PhotoPredictResponse) GetResults() []*PhotoPredictResponse_Result {
	if m != nil {
		return m.Results
	}
	return nil
}

type PhotoPredictResponse_Result struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
	ImageUrl             string   `protobuf:"bytes,2,opt,name=image_url,json=imageUrl" json:"image_url,omitempty"`
	AudioUrl             string   `protobuf:"bytes,3,opt,name=audio_url,json=audioUrl" json:"audio_url,omitempty"`
	VideoUrl             string   `protobuf:"bytes,4,opt,name=video_url,json=videoUrl" json:"video_url,omitempty"`
	ImageWidth           int32    `protobuf:"varint,5,opt,name=image_width,json=imageWidth" json:"image_width,omitempty"`
	ImageHeight          int32    `protobuf:"varint,6,opt,name=image_height,json=imageHeight" json:"image_height,omitempty"`
	AudioSize            int32    `protobuf:"varint,7,opt,name=audio_size,json=audioSize" json:"audio_size,omitempty"`
	AudioLen             int32    `protobuf:"varint,8,opt,name=audio_len,json=audioLen" json:"audio_len,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PhotoPredictResponse_Result) Reset()         { *m = PhotoPredictResponse_Result{} }
func (m *PhotoPredictResponse_Result) String() string { return proto.CompactTextString(m) }
func (*PhotoPredictResponse_Result) ProtoMessage()    {}
func (*PhotoPredictResponse_Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpc_7575a4de3a1e3c52, []int{5, 0}
}
func (m *PhotoPredictResponse_Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhotoPredictResponse_Result.Unmarshal(m, b)
}
func (m *PhotoPredictResponse_Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhotoPredictResponse_Result.Marshal(b, m, deterministic)
}
func (dst *PhotoPredictResponse_Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhotoPredictResponse_Result.Merge(dst, src)
}
func (m *PhotoPredictResponse_Result) XXX_Size() int {
	return xxx_messageInfo_PhotoPredictResponse_Result.Size(m)
}
func (m *PhotoPredictResponse_Result) XXX_DiscardUnknown() {
	xxx_messageInfo_PhotoPredictResponse_Result.DiscardUnknown(m)
}

var xxx_messageInfo_PhotoPredictResponse_Result proto.InternalMessageInfo

func (m *PhotoPredictResponse_Result) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *PhotoPredictResponse_Result) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

func (m *PhotoPredictResponse_Result) GetAudioUrl() string {
	if m != nil {
		return m.AudioUrl
	}
	return ""
}

func (m *PhotoPredictResponse_Result) GetVideoUrl() string {
	if m != nil {
		return m.VideoUrl
	}
	return ""
}

func (m *PhotoPredictResponse_Result) GetImageWidth() int32 {
	if m != nil {
		return m.ImageWidth
	}
	return 0
}

func (m *PhotoPredictResponse_Result) GetImageHeight() int32 {
	if m != nil {
		return m.ImageHeight
	}
	return 0
}

func (m *PhotoPredictResponse_Result) GetAudioSize() int32 {
	if m != nil {
		return m.AudioSize
	}
	return 0
}

func (m *PhotoPredictResponse_Result) GetAudioLen() int32 {
	if m != nil {
		return m.AudioLen
	}
	return 0
}

func init() {
	proto.RegisterType((*AuthRequest)(nil), "serverpb.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "serverpb.AuthResponse")
	proto.RegisterType((*GeoPosition)(nil), "serverpb.GeoPosition")
	proto.RegisterType((*SignSpot)(nil), "serverpb.SignSpot")
	proto.RegisterType((*PhotoPredictRequest)(nil), "serverpb.PhotoPredictRequest")
	proto.RegisterType((*PhotoPredictResponse)(nil), "serverpb.PhotoPredictResponse")
	proto.RegisterType((*PhotoPredictResponse_Result)(nil), "serverpb.PhotoPredictResponse.Result")
	proto.RegisterEnum("serverpb.SignSpot_SignSpotType", SignSpot_SignSpotType_name, SignSpot_SignSpotType_value)
	proto.RegisterEnum("serverpb.PhotoPredictRequest_PhotoType", PhotoPredictRequest_PhotoType_name, PhotoPredictRequest_PhotoType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Auth service

type AuthClient interface {
	Authenticate(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) Authenticate(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := grpc.Invoke(ctx, "/serverpb.Auth/Authenticate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Auth service

type AuthServer interface {
	Authenticate(context.Context, *AuthRequest) (*AuthResponse, error)
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverpb.Auth/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Authenticate(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "serverpb.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authenticate",
			Handler:    _Auth_Authenticate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}

// Client API for Predict service

type PredictClient interface {
	PredictPhoto(ctx context.Context, in *PhotoPredictRequest, opts ...grpc.CallOption) (*PhotoPredictResponse, error)
}

type predictClient struct {
	cc *grpc.ClientConn
}

func NewPredictClient(cc *grpc.ClientConn) PredictClient {
	return &predictClient{cc}
}

func (c *predictClient) PredictPhoto(ctx context.Context, in *PhotoPredictRequest, opts ...grpc.CallOption) (*PhotoPredictResponse, error) {
	out := new(PhotoPredictResponse)
	err := grpc.Invoke(ctx, "/serverpb.Predict/PredictPhoto", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Predict service

type PredictServer interface {
	PredictPhoto(context.Context, *PhotoPredictRequest) (*PhotoPredictResponse, error)
}

func RegisterPredictServer(s *grpc.Server, srv PredictServer) {
	s.RegisterService(&_Predict_serviceDesc, srv)
}

func _Predict_PredictPhoto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PhotoPredictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PredictServer).PredictPhoto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serverpb.Predict/PredictPhoto",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PredictServer).PredictPhoto(ctx, req.(*PhotoPredictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Predict_serviceDesc = grpc.ServiceDesc{
	ServiceName: "serverpb.Predict",
	HandlerType: (*PredictServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PredictPhoto",
			Handler:    _Predict_PredictPhoto_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_rpc_7575a4de3a1e3c52) }

var fileDescriptor_rpc_7575a4de3a1e3c52 = []byte{
	// 706 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xdd, 0x6e, 0xd3, 0x4a,
	0x10, 0x8e, 0x9d, 0x5f, 0x4f, 0xd2, 0x28, 0xda, 0xd3, 0x73, 0x64, 0xe5, 0x50, 0x1a, 0x8c, 0x4a,
	0x73, 0x95, 0x8b, 0x14, 0x71, 0xc3, 0x45, 0xd5, 0x4a, 0x28, 0x08, 0x15, 0x88, 0x9c, 0x02, 0x12,
	0x5c, 0x44, 0x6e, 0x3c, 0x72, 0x56, 0xd8, 0x5e, 0xd7, 0x5e, 0xb7, 0x69, 0xdf, 0x82, 0x57, 0xe0,
	0x8a, 0x97, 0xe1, 0x69, 0x78, 0x01, 0xb4, 0xb3, 0x4e, 0xe2, 0x22, 0xa8, 0xb8, 0x9b, 0xfd, 0x66,
	0x76, 0xf6, 0xdb, 0xef, 0x9b, 0x5d, 0xb0, 0xd2, 0x64, 0x31, 0x4a, 0x52, 0x21, 0x05, 0x6b, 0x65,
	0x98, 0x5e, 0x61, 0x9a, 0x5c, 0x38, 0x33, 0x68, 0x9f, 0xe4, 0x72, 0xe9, 0xe2, 0x65, 0x8e, 0x99,
	0x64, 0x0c, 0x6a, 0xb1, 0x17, 0xa1, 0x6d, 0x0c, 0x8c, 0xa1, 0xe5, 0x52, 0xcc, 0xfa, 0xd0, 0x4a,
	0xbc, 0x2c, 0xbb, 0x16, 0xa9, 0x6f, 0x9b, 0x84, 0x6f, 0xd6, 0x6c, 0x17, 0xea, 0x52, 0x7c, 0xc6,
	0xd8, 0xae, 0x52, 0x42, 0x2f, 0x9c, 0x4f, 0xd0, 0xd1, 0x4d, 0xb3, 0x44, 0xc4, 0x19, 0xb2, 0xc7,
	0xb0, 0x93, 0xe2, 0x65, 0xce, 0x53, 0x9c, 0x87, 0x22, 0xe0, 0x31, 0xb5, 0x6f, 0xb9, 0x9d, 0x02,
	0x3c, 0x53, 0xd8, 0xb6, 0x95, 0x59, 0x6a, 0xc5, 0x7a, 0x50, 0x8d, 0xb2, 0xa0, 0x68, 0xaf, 0x42,
	0x67, 0x02, 0xed, 0x09, 0x8a, 0xa9, 0xc8, 0xb8, 0xe4, 0x22, 0x56, 0xec, 0x42, 0x4f, 0x72, 0x99,
	0xfb, 0x9a, 0xb5, 0xe1, 0x6e, 0xd6, 0xec, 0x01, 0x58, 0xa1, 0x88, 0x03, 0x9d, 0x34, 0x29, 0xb9,
	0x05, 0x9c, 0x6f, 0x06, 0xb4, 0x66, 0x3c, 0x88, 0x67, 0x89, 0x90, 0xac, 0x0b, 0x26, 0xf7, 0xa9,
	0x41, 0xcd, 0x35, 0xb9, 0xbf, 0x11, 0xc2, 0x2c, 0x09, 0x71, 0x04, 0x35, 0x79, 0x93, 0x20, 0x91,
	0xe9, 0x8e, 0xf7, 0x47, 0x6b, 0x11, 0x47, 0xeb, 0x2e, 0x9b, 0xe0, 0xfc, 0x26, 0x41, 0x97, 0x8a,
	0xd9, 0x21, 0x54, 0x03, 0x14, 0x76, 0x6d, 0x60, 0x0c, 0xdb, 0xe3, 0x7f, 0xb7, 0x7b, 0x4a, 0x77,
	0x70, 0x55, 0x85, 0xd3, 0x87, 0x4e, 0x79, 0x3b, 0x03, 0x68, 0xbc, 0xce, 0x33, 0xcc, 0xa3, 0x5e,
	0xc5, 0xf9, 0x52, 0x85, 0x7f, 0xa6, 0x4b, 0x21, 0xc5, 0x34, 0x45, 0x9f, 0x2f, 0xe4, 0xda, 0xae,
	0xe7, 0x05, 0x23, 0x83, 0x18, 0x1d, 0x6e, 0xbb, 0xff, 0xa6, 0x58, 0x63, 0x25, 0x66, 0x0c, 0x6a,
	0xbe, 0x27, 0x3d, 0xba, 0x62, 0xc7, 0xa5, 0x98, 0x1d, 0x40, 0xf7, 0xc2, 0xcb, 0xf0, 0xd9, 0xd3,
	0x39, 0xc6, 0x0b, 0xe1, 0xa3, 0x4f, 0x97, 0x6d, 0xb9, 0x3b, 0x1a, 0x7d, 0xa1, 0xc1, 0xbf, 0xbe,
	0x14, 0x7b, 0x04, 0x1d, 0x6f, 0xa1, 0x9d, 0x97, 0xb8, 0x92, 0x76, 0x9d, 0xba, 0xb5, 0x0b, 0xec,
	0x1c, 0x57, 0x52, 0x0d, 0xc7, 0xba, 0xc4, 0xcb, 0x7d, 0x2e, 0xec, 0x86, 0x1e, 0x8e, 0x02, 0x3c,
	0x51, 0x58, 0xb9, 0xe8, 0x8a, 0xfb, 0x28, 0xec, 0xe6, 0x9d, 0xa2, 0xf7, 0x0a, 0x63, 0x7b, 0x00,
	0x91, 0xb7, 0x9a, 0x87, 0x3c, 0xe2, 0x32, 0xb3, 0x5b, 0x03, 0x63, 0x58, 0x77, 0xad, 0xc8, 0x5b,
	0x9d, 0x11, 0xa0, 0x27, 0x25, 0x0e, 0x72, 0x2f, 0x40, 0xdb, 0xd2, 0x73, 0xbc, 0x5e, 0x2b, 0x2d,
	0x32, 0x2e, 0xd1, 0x06, 0x6d, 0xb7, 0x8a, 0x9d, 0x3d, 0xb0, 0x36, 0x92, 0xb1, 0x26, 0x54, 0xa7,
	0x6f, 0x26, 0xbd, 0x8a, 0x0a, 0x5e, 0x4d, 0x27, 0x3d, 0xc3, 0xf9, 0x6e, 0xc2, 0xee, 0x5d, 0x99,
	0x8b, 0x69, 0x3f, 0x86, 0x66, 0x8a, 0x59, 0x1e, 0xca, 0xcc, 0x36, 0x06, 0xd5, 0x61, 0x7b, 0x7c,
	0xf0, 0x27, 0x5f, 0xf4, 0x86, 0x91, 0x4b, 0xd5, 0xee, 0x7a, 0x57, 0xff, 0x87, 0x01, 0x0d, 0x8d,
	0x29, 0x5e, 0xa4, 0x5b, 0xf1, 0x1e, 0x55, 0xcc, 0xfe, 0x07, 0x8b, 0x47, 0x5e, 0x80, 0xf3, 0x3c,
	0x0d, 0xd7, 0x0f, 0x92, 0x80, 0x77, 0x69, 0xa8, 0x92, 0xa4, 0x22, 0x25, 0xf5, 0xab, 0x69, 0x11,
	0x50, 0x24, 0x49, 0x3d, 0x4a, 0xd6, 0x74, 0x92, 0x00, 0x95, 0xdc, 0x87, 0xb6, 0x6e, 0x7b, 0xcd,
	0x7d, 0xb9, 0x24, 0xa7, 0xea, 0x2e, 0x10, 0xf4, 0x41, 0x21, 0xca, 0x4b, 0x5d, 0xb0, 0x44, 0x1e,
	0x2c, 0x25, 0xf9, 0x54, 0x77, 0xf5, 0xa6, 0x97, 0x04, 0x29, 0x07, 0xf4, 0xe9, 0x19, 0xbf, 0x45,
	0xf2, 0xa8, 0xee, 0x6a, 0x3e, 0x33, 0x7e, 0x8b, 0x5b, 0x72, 0x21, 0xc6, 0x85, 0x3f, 0x9a, 0xdc,
	0x19, 0xc6, 0xe3, 0x09, 0xd4, 0xd4, 0xa7, 0xc1, 0x8e, 0xf5, 0xe7, 0x81, 0xb1, 0xe4, 0x0b, 0x4f,
	0x22, 0x2b, 0x8d, 0x57, 0xe9, 0xa7, 0xea, 0xff, 0xf7, 0x2b, 0xac, 0xc5, 0x74, 0x2a, 0xe3, 0x8f,
	0xd0, 0x2c, 0x14, 0x66, 0x6f, 0xa1, 0x53, 0x84, 0x24, 0x3c, 0xdb, 0xbb, 0xf7, 0x85, 0xf4, 0x1f,
	0xde, 0x6f, 0x94, 0x53, 0x39, 0x7d, 0x02, 0xdd, 0x85, 0x88, 0x46, 0x1e, 0x97, 0x22, 0x4f, 0x47,
	0x69, 0xb2, 0x38, 0xb5, 0xd4, 0xe9, 0x53, 0xf5, 0xab, 0x4e, 0x8d, 0xaf, 0x66, 0x43, 0x67, 0x2e,
	0x1a, 0xf4, 0xcf, 0x1e, 0xfd, 0x0c, 0x00, 0x00, 0xff, 0xff, 0xcd, 0x04, 0x69, 0x31, 0x74, 0x05,
	0x00, 0x00,
}
