# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import rpc_pb2 as rpc__pb2


class AuthStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Authenticate = channel.unary_unary(
        '/serverpb.Auth/Authenticate',
        request_serializer=rpc__pb2.AuthRequest.SerializeToString,
        response_deserializer=rpc__pb2.AuthResponse.FromString,
        )


class AuthServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Authenticate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AuthServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Authenticate': grpc.unary_unary_rpc_method_handler(
          servicer.Authenticate,
          request_deserializer=rpc__pb2.AuthRequest.FromString,
          response_serializer=rpc__pb2.AuthResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'serverpb.Auth', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class PredictStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.PredictPhoto = channel.unary_unary(
        '/serverpb.Predict/PredictPhoto',
        request_serializer=rpc__pb2.PhotoPredictRequest.SerializeToString,
        response_deserializer=rpc__pb2.PhotoPredictResponse.FromString,
        )


class PredictServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def PredictPhoto(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PredictServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'PredictPhoto': grpc.unary_unary_rpc_method_handler(
          servicer.PredictPhoto,
          request_deserializer=rpc__pb2.PhotoPredictRequest.FromString,
          response_serializer=rpc__pb2.PhotoPredictResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'serverpb.Predict', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
